### ISSUE TITLE
Matter Server question

### ISSUE THREAD

**Issue by frantathefranta** [dcplaya/home-ops#8633]
Hey, I found your repo through the kubesearch site since you are one of two people who have the Home Assistant Matter container deployed. I'm wondering if it's working for you (i.e. you can add Matter devices to Home Assistant through it) and if there's anything special you've done to make it work? I notice you are using Multus CNI on top of Cilium, which I'm not. 
Thanks for any and all advice!

**Comment by dcplaya** [comment]
@frantathefranta 

I have not gotten it to work, ever. 
I only have 1 device supported by matter, and its my Nest thermostat. It's always failed to pair though.

Currently, that container fails to boot, so I disabled it for now, until I get more time to debug why it wont even boot. 

I have Multus enabled for it to try and pair better with devices on my IoT network, but that didn't seem to make any difference.

**Comment by frantathefranta** [comment]
Ah good to know. I managed to make it boot and connect it to Home Assistant running in the cluster. I could see it getting the initial pairing request from my phone (when onboarding a device in HASS), but nothing afterwards. I'm guessing there's an issue with IPv6 configuration somewhere. I see that the pod gets a link-local address which should be enough (I think, that's the minimum my HASS VM has and it works with Matter), but there's probably more required with Kubernetes.
